### ISSUE TITLE
[Feature] Ability to move terminal

### ISSUE THREAD

**Issue by ghost** [jcubic/jquery.terminal-www#10]
Hi 👋 

How would I go by implementing on click one can move the console by click and hold the header?

**Comment by jcubic** [comment]
If you mean like chat window on a website, it's created with [dterm plugin](https://github.com/jcubic/jquery.terminal/blob/master/js/dterm.js) which is one of the examples. You can include that file and use it just like terminal - same arguments. It use [jQuery UI dialog](https://jqueryui.com/dialog/) for that.

You can also implement something like this yourself using [UI dragable](https://jqueryui.com/draggable/).

**Comment by ghost** [comment]
Thank you
