### ISSUE TITLE
Document CSS vars with IE11

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal-www#12]
There is projects [css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) and changing colors works with IE11, this need to be added to documentation. (css vars need to be set on `:root`).

**Comment by nuxodin** [comment]
Have a look at my polyfill where you can define variable on every element:
https://github.com/nuxodin/ie11CustomProperties

**Comment by jcubic** [comment]
@nuxodin thanks, will check your project.

**Comment by jcubic** [comment]
Since IE is dead I don't think this is needed anymore.
