### ISSUE TITLE
[bug] typing animation error for chinese char

### ISSUE THREAD

**Issue by Relaxself** [jcubic/jquery.terminal-www#31]
thanks for this project.
when I use this to echo some chinese with typing animation, I got a bug, just like below.

![terminaltypingerror](https://github.com/user-attachments/assets/bba8490b-bfe1-4d49-b9d8-821c68a1e4f1)

can you fix this?

**Comment by jcubic** [comment]
Thanks for the bug report, can you create it in the main repo?

https://github.com/jcubic/jquery.terminal

I will take a look.

**Comment by jcubic** [comment]
When you create an issue, please provide a reproduction.

I was not able to reproduce the issue you're having:

https://codepen.io/jcubic/pen/oNKveBj?editors=0010

**Comment by jcubic** [comment]
I was able to reproduce your issue, this is because you didn't include `wcwidth` file, that is required for Chinese and Japanese characters.

You can install it from npm or grab from this CDN link:

https://cdn.jsdelivr.net/gh/jcubic/static/js/wcwidth.js

**Comment by jcubic** [comment]
It's documented on a Wiki:

https://github.com/jcubic/jquery.terminal/wiki/Chinese-and-Japanese-character-support
