### ISSUE TITLE
Unable to show icons to various button to direct social media websites.

### ISSUE THREAD

**Issue by sunnyp123** [jcubic/jquery.terminal-www#6]
![image](https://user-images.githubusercontent.com/26931075/38743131-ef252442-3f5b-11e8-9e66-ab5b7d2bf8fe.png)

**Comment by PAPERPANKS** [comment]
That's a nice find @sunnyp123. I will try to find this bug.

**Comment by DInesh51297** [comment]
i have fixed this issue check my code #8

**Comment by jcubic** [comment]
Thanks for the find.
